language: node_js
os:
  - linux
  - windows
  - osx
matrix:
  allow_failures:
    - os: windows
node_js:
- "7"
- "8"
env:
  global:
  - GH_REPO="marabesi/trello-to-excel"
script:
  - npm install
  - npm run test-ci
